name: Build Express API Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [docker]

    steps:
      - name: Checkout repository
        run: |
          git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .

      - name: Docker login
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry-docker.weg.net -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          DOCKER_IMAGE="server:5000/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo "DOCKER_IMAGE=$DOCKER_IMAGE"
          docker build \
          --build-arg REGISTRY_USERNAME=${{ secrets.REGISTRY_USERNAME }} \
          --build-arg REGISTRY_PASSWORD=${{ secrets.REGISTRY_PASSWORD }} \
          -t $DOCKER_IMAGE .
           docker push $DOCKER_IMAGE
