name: Build Express API Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [docker]

    steps:
      - name: Checkout repository
        run: |
          git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH }}"/"${{ gitea.repository }}".git .

      - name: Docker login
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry-docker.weg.net -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
          --build-arg REGISTRY_USERNAME=${{ secrets.REGISTRY_USERNAME }} \
          --build-arg REGISTRY_PASSWORD=${{ secrets.REGISTRY_PASSWORD }} \
          -t registry-docker.weg.net/${{ gitea.repository }}:${{ gitea.run_id }} .

      # - name: Test Docker image
      #   run: |
      #     docker run --rm -d -p 3001:3001 --name test-api my-express-api:latest
      #     sleep 5
      #     curl -f http://localhost:3001/ || exit 1
      #     docker stop test-api
