name: Calculator API Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: [docker]
    steps:
      - name: Cloning Repository
        run: |
          git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .
          echo http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git

      - name: Installing Node.js 22 (via direct download, sem depender de apk)
        run: |
          set -e
          echo "⚙️ Baixando Node.js 22 diretamente (sem usar repositórios APK)..."

          # Verifica se wget está disponível, caso contrário tenta usar busybox
          if command -v wget >/dev/null 2>&1; then
            echo "✅ wget encontrado. Baixando Node.js..."
            wget -q https://unofficial-builds.nodejs.org/download/release/v22.9.0/node-v22.9.0-linux-x64-musl.tar.xz -O node.tar.xz
          else
            echo "⚠️ wget não encontrado. Tentando via busybox..."
            busybox wget -q https://unofficial-builds.nodejs.org/download/release/v22.9.0/node-v22.9.0-linux-x64-musl.tar.xz -O node.tar.xz
          fi

          tar -xJf node.tar.xz -C /usr/local --strip-components=1
          rm node.tar.xz

          node -v
          npm -v
          echo "✅ Node.js instalado com sucesso!"

      - name: Running Tests
        run: |
          npm ci
          npm run test
  
  build:
    runs-on: [docker]
    needs: test
    steps:
      - name: Cloning Repository
        run: |
          git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .
          echo http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git

      - name: Registry Authentication
        run: echo "${{ secrets.ACTION_PASSWORD }}" | docker login ${{ secrets.BASE_PATH_REGISTRY }} -u "${{ secrets.ACTION_USERNAME }}" --password-stdin

      - name: Building Docker Image
        run: |
          DOCKER_IMAGE="${{ secrets.BASE_PATH_REGISTRY }}/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo $DOCKER_IMAGE
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

  deploy:
    runs-on: [docker]
    needs: build
    steps:
      - name: Registry Authentication
        run: echo "${{ secrets.ACTION_PASSWORD }}" | docker login ${{ secrets.BASE_PATH_REGISTRY }} -u "${{ secrets.ACTION_USERNAME }}" --password-stdin

      - name: Getting Docker Image
        run: |
          DOCKER_IMAGE="${{ secrets.BASE_PATH_REGISTRY }}/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo $DOCKER_IMAGE
