name: Calculator API Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: [docker]
    steps:
      - name: Cloning Repository
        run: |
          git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .
          echo http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git

      - name: Installing Node
        run: |
          apk update -v
          wget https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
          nslookup dl-cdn.alpinelinux.org
          # apk add --no-cache curl bash git
          # echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
          # echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
          # apk update
          # apk add --no-cache nodejs-current npm
          # node -v
          # npm -v

      - name: Running Tests
        run: |
          npm ci
          npm run test
  
  build:
    runs-on: [docker]
    needs: test
    steps:
      - name: Cloning Repository
        run: |
          git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .
          echo http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git

      - name: Registry Authentication
        run: echo "${{ secrets.ACTION_PASSWORD }}" | docker login ${{ secrets.BASE_PATH_REGISTRY }} -u "${{ secrets.ACTION_USERNAME }}" --password-stdin

      - name: Building Docker Image
        run: |
          DOCKER_IMAGE="${{ secrets.BASE_PATH_REGISTRY }}/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo $DOCKER_IMAGE
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

  deploy:
    runs-on: [docker]
    needs: build
    steps:
      - name: Registry Authentication
        run: echo "${{ secrets.ACTION_PASSWORD }}" | docker login ${{ secrets.BASE_PATH_REGISTRY }} -u "${{ secrets.ACTION_USERNAME }}" --password-stdin

      - name: Getting Docker Image
        run: |
          DOCKER_IMAGE="${{ secrets.BASE_PATH_REGISTRY }}/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo $DOCKER_IMAGE
