name: Calculator API Pipeline

on:
  push:
    branches:
      - master

jobs:
  # test:
  #   runs-on: [docker]
  #   steps:
  #     - name: Installing Node
  #       run: |
  #         apk add nodejs-current npm

  #     - name: Cloning Repository
  #       run: |
  #         git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .
  #         echo http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git

  #     - name: Running Tests
  #       run: |
  #         npm ci
  #         npm run test
  
  build:
    runs-on: [docker]
    container:
      image: docker:latest
    # needs: test
    steps:
      - name: Cloning Repository
        run: |
          git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .
          echo http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git

      - name: Registry Authentication
        run: echo "${{ secrets.ACTION_PASSWORD }}" | docker login ${{ secrets.BASE_PATH_REGISTRY }} -u "${{ secrets.ACTION_USERNAME }}" --password-stdin

      - name: Building Docker Image
        run: |
          DOCKER_IMAGE="${{ secrets.BASE_PATH_REGISTRY }}/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo $DOCKER_IMAGE
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

  deploy:
    runs-on: [docker]
    needs: build
    steps:
      - name: Registry Authentication
        run: echo "${{ secrets.ACTION_PASSWORD }}" | docker login ${{ secrets.BASE_PATH_REGISTRY }} -u "${{ secrets.ACTION_USERNAME }}" --password-stdin

      - name: Getting Docker Image
        run: |
          export DOCKER_IMAGE="${{ secrets.BASE_PATH_REGISTRY }}/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> .env

      - name: Pulling Docker Image
        run: |
          source .env
          docker pull "$DOCKER_IMAGE"

      - name: Running Docker Container
        run: |
          source .env
          docker run --rm -it -p 3001:3001 "$DOCKER_IMAGE"
          # docker rm -f calculator-api || true
          # docker run -d \
          #   --name calculator-api \
          #   --network gitea \
          #   -p 3001:3001 \
          #   --restart always \
          #   "$DOCKER_IMAGE"
