name: Calculator API Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: [docker]
    container:
      image: registry-docker.weg.net/node:22-bookworm
    steps:
      # - name: Cloning Repository
      #   run: |
      #     git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .
      #     echo http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git

      - name: Installing Git
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git
          rm -rf /var/lib/apt/lists/*

      - name: Running Tests
        run: |
          npm ci
          npm run test
  
  build:
    runs-on: [docker]
    needs: test
    steps:
      - name: Cloning Repository
        run: |
          git clone --branch master http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git .
          echo http://"${{ secrets.ACTION_USERNAME }}":"${{ secrets.ACTION_PASSWORD }}"@"${{ secrets.BASE_PATH_SERVER }}"/"${{ gitea.repository }}".git

      - name: Registry Authentication
        run: echo "${{ secrets.ACTION_PASSWORD }}" | docker login ${{ secrets.BASE_PATH_REGISTRY }} -u "${{ secrets.ACTION_USERNAME }}" --password-stdin

      - name: Building Docker Image
        run: |
          DOCKER_IMAGE="${{ secrets.BASE_PATH_REGISTRY }}/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo $DOCKER_IMAGE
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

  deploy:
    runs-on: [docker]
    needs: build
    steps:
      - name: Registry Authentication
        run: echo "${{ secrets.ACTION_PASSWORD }}" | docker login ${{ secrets.BASE_PATH_REGISTRY }} -u "${{ secrets.ACTION_USERNAME }}" --password-stdin

      - name: Getting Docker Image
        run: |
          DOCKER_IMAGE="${{ secrets.BASE_PATH_REGISTRY }}/${{ gitea.repository }}:runid${{ gitea.run_id }}"
          echo $DOCKER_IMAGE
